name: pypi-build-and-deploy

# Only run this workflow when a diepvries/* tag gets pushed
on:
  push:
    tags:
      - diepvries/*

jobs:
  deploy-to-pypi:
    runs-on: ubuntu-22.04

    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.9
      - name: Install dependencies
        run: python -m pip install tox
      - name: Run tox build
        run: python -m tox -e build
      - name: Run tox upload
        run: python -m tox -e upload
