name: pypi-build-and-deploy
on:
  # Only run this workflow when a commit with a diepvries/* tag gets pushed to the default branch
  push:
    branches: [$default-branch]
    tags: [diepvries/*]
jobs:
  run-ci:
    runs-on: ubuntu-22.04

    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          sudo apt update
          python -m pip install tox
      - name: Run tox
        run: python -m tox -e build -e upload
